name: Check lacked predefined variable and functions 

on:
  schedule:
    # 0:00 UTC (9:00 JST)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-documentation-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: run checker
        id: checking
        working-directory: cmd/documentation-checker
        run: |
          go run . > ./lacked.txt
          LACKED=$(cat ./lacked.txt)
          if [ "$LACKED" != "" ]; then
            echo "lacked=1" >> $GITHUB_OUTPUT
          fi
      - name: create issue if exists
        if: ${{ steps.checking.outputs.lacked == '1' }}
        run: |
          ISSUE=$(gh issue list -l automated --json title)
          LACKED=$(cat ./lacked.txt)
          if [ "$ISSUE" == "[]" ]; then
            gh issue create \
              -b "$LACKED" \
              -a ysugimoto \
              -t "[Automated] Need to implement new variables/functions" \
              -l automated
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

